In [1]:
# working with APIs
# Using requests

In [2]:
!pip install requests

Requirement already satisfied: requests in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (from requests) (2025.8.3)

In [3]:
import requests

In [4]:
URL="https://stephen-king-api.onrender.com/api/books"

res=requests.get(URL)

In [5]:
res

In [10]:
json_data=res.json()

In [14]:
import pandas as pd
df=pd.json_normalize(json_data["data"])
df=df[["id","Title","Year","ISBN"]]

In [15]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [16]:
# Web Scraping: Involves programmatically extracting data from websites
# 1. BeautifulSoup
# 2. Selenium

# toscrape.com
# scarpethissite.com

In [19]:
import requests

URL="https://www.scrapethissite.com/pages/simple/"

res=requests.get(URL)

In [20]:
res

In [25]:
if res.status_code==200:
    print(res.headers)

with open("scraped_data/data1.html","w") as f:
    f.write(res.text)

{'Date': 'Mon, 16 Mar 2026 15:00:28 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=xg9UBN2eiwwcjPQ%2FLm%2BpW1XIkZBmttAMEPQXsTw3ugM%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1773673227"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=xg9UBN2eiwwcjPQ%2FLm%2BpW1XIkZBmttAMEPQXsTw3ugM%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1773673227"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9dd4a0a4de8a1849-DEL', 'alt-svc': 'h3=":443"; ma=86400'}

In [30]:
# BeautifulSoup Library & lxml

!pip install beautifulsoup4
!pip install lxml

from bs4 import BeautifulSoup

with open("scraped_data/data1.html","r") as f:
    html_content=f.read()

soup=BeautifulSoup(html_content,"lxml")

Requirement already satisfied: beautifulsoup4 in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (from beautifulsoup4) (4.12.2)
Requirement already satisfied: lxml in /Users/ayushkumarpal/miniconda3/lib/python3.13/site-packages (6.0.2)

In [32]:
 soup

In [33]:
# trying to extract country name and its corresponding population

all_h3=soup.find_all("h3")

all_countries=[]

for h3 in all_h3:
    name=h3.get_text(strip=True)

    population=h3.find_next("div").select("span.country-population")[0].get_text(strip=True)

    all_countries.append([name,population])

In [38]:
# all_countries

import pandas as pd

df=pd.DataFrame(all_countries,columns=["Name","Population"])

In [39]:
df

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [40]:
df.to_csv("cleaned_data/data.csv",index=False)